/**
 * LLM integration types for Monster Mash
 *
 * WHY: These types define the contract for LLM interactions with Claude Haiku 4.5.
 * Validated through Spike 2-3, including verbalized sampling outputs and
 * personality system prompts.
 */

/**
 * Verbalized Sampling output - multiple options with confidence scores
 *
 * WHY: FR-014 to FR-017a require agents to generate 3-5 options with confidence
 * scores. This is the core output format for all LLM-based agent decisions.
 * Validated in Spike 2-3.
 */
export interface VerbalizeSamplingOutput<T = any> {
  /** List of options generated by LLM (minimum 3, recommended 3-5) */
  options: Array<{
    /** Human-readable description of this option */
    description: string;
    /** Confidence score 0.0-1.0 (higher = more confident) */
    confidence: number;
    /** Structured data for this option (theme details, menu item, etc.) */
    data?: T;
  }>;
  /** Optional metadata about generation process */
  metadata?: {
    /** Token usage for this generation */
    tokenUsage?: TokenUsage;
    /** How long did generation take? (milliseconds) */
    latencyMs?: number;
    /** Which personality was used? (if any) */
    personality?: string;
  };
}

/**
 * Token usage tracking for cost monitoring
 *
 * WHY: SC-016 to SC-019 require cost monitoring and staying under budget.
 * Claude API returns token counts which we use to calculate costs.
 * Validated in Spike 2 ($0.02-0.05 per session).
 */
export interface TokenUsage {
  /** Number of input tokens (prompt + context) */
  inputTokens: number;
  /** Number of output tokens (LLM response) */
  outputTokens: number;
  /** Total tokens (input + output) */
  totalTokens: number;
}

/**
 * LLM response wrapper with error handling
 *
 * WHY: LLM calls can fail (rate limits, network errors, invalid JSON). We need
 * graceful degradation with fallback templates (FR-050d, validated in Spike 2).
 */
export interface LLMResponse<T = any> {
  /** Was the LLM call successful? */
  success: boolean;
  /** Parsed data from LLM response (if successful) */
  data?: T;
  /** Error message (if failed) */
  error?: string;
  /** Token usage tracking */
  tokenUsage?: TokenUsage;
  /** Latency in milliseconds */
  latencyMs: number;
  /** Source of response ('llm' | 'fallback') */
  source: "llm" | "fallback";
}

/**
 * Personality configuration for system prompts
 *
 * WHY: FR-051 to FR-053c require optional personality system prompts that
 * shape agent behavior. Spike 3 validated 3 personalities create dramatic
 * behavioral differences.
 */
export interface Personality {
  /** Personality identifier (e.g., 'frugal', 'perfectionist', 'adventurous') */
  id: "frugal" | "perfectionist" | "adventurous" | "default";
  /** Human-readable name */
  name: string;
  /** System prompt text that shapes LLM behavior */
  systemPrompt: string;
  /** Short description of this personality's characteristics */
  description: string;
}

/**
 * LLM request configuration
 *
 * WHY: Encapsulates all parameters needed for an LLM call. Makes it easy to
 * add retry logic, logging, and fallback handling in anthropic-client.ts.
 */
export interface LLMRequest {
  /** User prompt text */
  prompt: string;
  /** Optional system prompt (personality or base instructions) */
  systemPrompt?: string;
  /** Maximum tokens to generate */
  maxTokens?: number;
  /** Temperature (0.0-1.0, higher = more creative) */
  temperature?: number;
  /** Model to use (default: 'claude-haiku-4-5') */
  model?: string;
  /** Expected response format (for JSON mode) */
  responseFormat?: "json" | "text";
}

/**
 * Cost calculation result
 *
 * WHY: SC-019 requires cost tracking. Claude Haiku 4.5 pricing is $1 input /
 * $5 output per million tokens. Helper function will calculate total cost.
 */
export interface CostEstimate {
  /** Input cost in USD */
  inputCost: number;
  /** Output cost in USD */
  outputCost: number;
  /** Total cost in USD */
  totalCost: number;
  /** Number of LLM calls made */
  callCount: number;
  /** Average cost per call */
  avgCostPerCall: number;
}

/**
 * Pricing configuration for cost calculations
 *
 * WHY: Claude Haiku 4.5 pricing validated in Spike 2. Making this configurable
 * allows easy updates if pricing changes or if we switch models.
 */
export interface LLMPricing {
  /** Model name (e.g., 'claude-haiku-4-5') */
  model: string;
  /** Cost per million input tokens in USD */
  inputPricePerMillion: number;
  /** Cost per million output tokens in USD */
  outputPricePerMillion: number;
}
